# Generated by Django 5.1.2 on 2024-10-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='estado',
            field=models.CharField(choices=[('R', 'Rentado'), ('D', 'Devuelto'), ('T', 'Devuelto tarde'), ('P', 'Sin devolve aun')], default='R', editable=False, max_length=20, verbose_name='Estado de la renta'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de devolución'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='fecha_devolucion_estimada',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Fecha de devolución estimada'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='id_renta',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Identificador de renta'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='pumapuntos_obtenidos',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='PumaPuntos obtenidos de esta renta'),
        ),
    ]
