# Generated by Django 5.1.2 on 2024-10-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superusuario',
            options={'permissions': [('ver_productos', 'Puede ver productos'), ('agregar_producto', 'Puede agregar productos'), ('editar_producto', 'Puede editar productos'), ('eliminar_producto', 'Puede eliminar productos'), ('añadir_usuario', 'Puede añadir usuarios'), ('editar_usuario', 'Puede editar usuarios'), ('eliminar_usuario', 'Puede eliminar usuarios'), ('ver_usuarios', 'Puede ver usuarios'), ('sumar_pumapuntos', 'Puede sumar puma puntos'), ('rentar_producto', 'Puede rentar productos')]},
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='carrera',
            field=models.CharField(choices=[('actuaria', 'Actuaría'), ('biologia', 'Biología'), ('computacion', 'Ciencias de la Computación'), ('ciencias_de_la_tierra', 'Ciencias de la Tierra'), ('fisica', 'Física'), ('fisica_biomedica', 'Física Biomédica'), ('manejo_zonas_costeras', 'Manejo Sustentable de Zonas Costeras'), ('matematicas', 'Matemáticas'), ('matematicas_aplicadas', 'Matemáticas Aplicadas'), ('academico', 'Acádemico Ciencias')], max_length=100, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='celular',
            field=models.CharField(max_length=10, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='numero_cuenta',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='superusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('proveedor', 'Proveedor'), ('usuario', 'Usuario')], max_length=20, verbose_name='Rol'),
        ),
    ]
