# Generated by Django 5.1.2 on 2024-10-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_superusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superusuario',
            options={'permissions': [('ver_productos', 'Puede ver productos'), ('agregar_producto', 'Puede agregar productos'), ('editar_producto', 'Puede editar productos'), ('eliminar_producto', 'Puede eliminar productos'), ('agregar_usuario', 'Puede añadir usuarios'), ('editar_usuario', 'Puede editar usuarios'), ('eliminar_usuario', 'Puede eliminar usuarios'), ('ver_usuarios', 'Puede ver usuarios'), ('sumar_pumapuntos', 'Puede sumar puma puntos'), ('rentar_producto', 'Puede rentar productos')]},
        ),
    ]
