# Generated by Django 5.1.2 on 2024-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_superusuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='superusuario',
            name='correo',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
