# Generated by Django 5.1.2 on 2024-10-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_superusuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='superusuario',
            name='contrasenia_temp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
