# Generated by Django 5.1.2 on 2024-10-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Código del producto'),
        ),
    ]
